### ISSUE TITLE
error while installing face_recognition

### ISSUE THREAD

**Issue by SijinJohn** [abhishekmalle/FaceCheck#1]
Hi i am getting error while instaling face_recognition.
Traceback (most recent call last):
    File "C:\Users\SIJIN~1.JOH\AppData\Local\Temp\pip-install-ou6izibi\dlib\setup.py", line 118, in get_cmake_version
      out = subprocess.check_output(['cmake', '--version'])
    File "c:\users\sijin.john\appdata\local\programs\python\python36\lib\subprocess.py", line 336, in check_output
      **kwargs).stdout
    File "c:\users\sijin.john\appdata\local\programs\python\python36\lib\subprocess.py", line 403, in run
      with Popen(*popenargs, **kwargs) as process:
    File "c:\users\sijin.john\appdata\local\programs\python\python36\lib\subprocess.py", line 709, in __init__
      restore_signals, start_new_session)
    File "c:\users\sijin.john\appdata\local\programs\python\python36\lib\subprocess.py", line 997, in _execute_child
      startupinfo)
  FileNotFoundError: [WinError 2] The system cannot find the file specified

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\SIJIN~1.JOH\AppData\Local\Temp\pip-install-ou6izibi\dlib\setup.py", line 257, in <module>
      'Topic :: Software Development',
    File "c:\users\sijin.john\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "c:\users\sijin.john\appdata\local\programs\python\python36\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\users\sijin.john\appdata\local\programs\python\python36\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "c:\users\sijin.john\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "c:\users\sijin.john\appdata\local\programs\python\python36\lib\site-packages\wheel\bdist_wheel.py", line 188, in run
      self.run_command('build')
    File "c:\users\sijin.john\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\sijin.john\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "c:\users\sijin.john\appdata\local\programs\python\python36\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\users\sijin.john\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\sijin.john\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\SIJIN~1.JOH\AppData\Local\Temp\pip-install-ou6izibi\dlib\setup.py", line 127, in run
      cmake_version = self.get_cmake_version()
    File "C:\Users\SIJIN~1.JOH\AppData\Local\Temp\pip-install-ou6izibi\dlib\setup.py", line 123, in get_cmake_version
      "\n*******************************************************************\n")
  RuntimeError:
  *******************************************************************
   CMake must be installed to build the following extensions: dlib
  *******************************************************************

  ----------------------------------------
  Failed building wheel for dlib
  Running setup.py clean for dlib
  Running setup.py bdist_wheel for face-recognition-models ... done
  Stored in directory: C:\Users\sijin.john\AppData\Local\pip\Cache\wheels\d2\99\18\59c6c8f01e39810415c0e63f5bede7d83dfb0ffc039865465f
Successfully built face-recognition-models
Failed to build dlib
Installing collected packages: Click, dlib, face-recognition-models, face-recognition
  Running setup.py install for dlib ... error
    Complete output from command c:\users\sijin.john\appdata\local\programs\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\SIJIN~1.JOH\\AppData\\Local\\Temp\\pip-install-ou6izibi\\dlib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\SIJIN~1.JOH\AppData\Local\Temp\pip-record-iep41c2h\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    package init file 'dlib\__init__.py' not found (or not a regular file)
    running build_ext
    Traceback (most recent call last):
      File "C:\Users\SIJIN~1.JOH\AppData\Local\Temp\pip-install-ou6izibi\dlib\setup.py", line 118, in get_cmake_version
        out = subprocess.check_output(['cmake', '--version'])
      File "c:\users\sijin.john\appdata\local\programs\python\python36\lib\subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "c:\users\sijin.john\appdata\local\programs\python\python36\lib\subprocess.py", line 403, in run
        with Popen(*popenargs, **kwargs) as process:
      File "c:\users\sijin.john\appdata\local\programs\python\python36\lib\subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "c:\users\sijin.john\appdata\local\programs\python\python36\lib\subprocess.py", line 997, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\SIJIN~1.JOH\AppData\Local\Temp\pip-install-ou6izibi\dlib\setup.py", line 257, in <module>
        'Topic :: Software Development',
      File "c:\users\sijin.john\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\sijin.john\appdata\local\programs\python\python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\sijin.john\appdata\local\programs\python\python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\sijin.john\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\sijin.john\appdata\local\programs\python\python36\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\sijin.john\appdata\local\programs\python\python36\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\sijin.john\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\sijin.john\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\sijin.john\appdata\local\programs\python\python36\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\sijin.john\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\sijin.john\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\SIJIN~1.JOH\AppData\Local\Temp\pip-install-ou6izibi\dlib\setup.py", line 127, in run
        cmake_version = self.get_cmake_version()
      File "C:\Users\SIJIN~1.JOH\AppData\Local\Temp\pip-install-ou6izibi\dlib\setup.py", line 123, in get_cmake_version
        "\n*******************************************************************\n")
    RuntimeError:
    *******************************************************************
     CMake must be installed to build the following extensions: dlib
    *******************************************************************

    ----------------------------------------
Command "c:\users\sijin.john\appdata\local\programs\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\SIJIN~1.JOH\\AppData\\Local\\Temp\\pip-install-ou6izibi\\dlib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\SIJIN~1.JOH\AppData\Local\Temp\pip-record-iep41c2h\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\SIJIN~1.JOH\AppData\Local\Temp\pip-install-ou6izi

**Comment by SijinJohn** [comment]
can i get to contact you immediately

**Comment by SijinJohn** [comment]
hi
I tried this model but it randomly reads unknown people to be valid people??
what can be done???

**Comment by YuleZhang** [comment]
have your solved this problems?

**Comment by SijinJohn** [comment]
No..... Do u have any solution???

**Comment by YuleZhang** [comment]
I solved this problem after installing the cmake、boost packages last night.

**Comment by SijinJohn** [comment]
Does the model recognize faces accurately for more than 20 people???

**Comment by YuleZhang** [comment]
sorry, I haven't try that. I just test the result of the recognization by video capture.
